# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  GREETING: Hello, world!

tasks:
  default:
    desc: Print a greeting message
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  dev:
    desc: Start GO backend with hot reload and frontend dev server
    deps:
      - task: backend
      - task: frontend

  backend:
    desc: Start GO backend with hot reload
    dir: ./backend
    cmds:
      - air
    
  frontend:
    desc: Start frontend dev server
    dir: ./frontend
    cmds:
      #- npm install
      - npm run dev

  frontend-api:
    desc: Generate client api from docs/openapi
    dir: ./frontend
    cmds:
      - npm run openapi-ts

  build:frontend:
    desc: Build frontend
    dir: ./frontend
    cmds:
      - npm run generate
  
  build:backend:
    dir: backend
    cmds:
      - go clean -cache
      - go build -v -o tmp/main ./cmd/main.go

  sync:assets:
    desc: Move frontend build to backend server folder
    dir: ./
    cmds:
      - rm -rf backend/internal/server/dist
      # The -L flag dereferences symlinks (turns them into real files)
      - cp -rL frontend/.output/public backend/internal/server/dist
  
  