# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  GREETING: Hello, world!

tasks:
  default:
    desc: Print a greeting message
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  setup:
    desc: Install required tooling
    dir: ./
    cmds:
    - task: _setup:backend
    - task: _setup:frontend

  _setup:backend:
    desc: Only install backend tooling if the dependencies have changedd
    dir: ./backend
    sources:
      - go.mod
      - go.sum
    cmds:
      - go install -x tool
      - echo "finished installing go tools"

  _setup:frontend:
    desc: Only install frontend tooling if the dependencies have changedd
    dir: ./frontend
    sources:
      - package.json
      - package-lock.json
    cmds:
      - npm install
      - echo "finished installing npm dependencies"

  dev:
    desc: Start GO backend with hot reload and frontend dev server
    deps:
      - task: backend
      - task: frontend

  backend:
    desc: Start GO backend with hot reload
    dir: ./backend
    cmds:
      - task: _setup:backend
      - air
    
  frontend:
    desc: Start frontend dev server
    dir: ./frontend
    cmds:
      - task: _setup:frontend
      - npm run dev

  frontend-api:
    desc: Generate client api from docs/openapi
    dir: ./frontend
    cmds:
      - npm run openapi-ts





  _sync:assets:
    desc: Move frontend build to backend server folder
    dir: ./
    cmds:
      - rm -rf backend/internal/server/dist
      # The -L flag dereferences symlinks (turns them into real files)
      - cp -rL frontend/.output/public backend/internal/server/dist
  
  

  _build:frontend:
    desc: Build frontend
    dir: ./frontend
    cmds:
      - npm install
      - npm run generate
  
  _build:backend:
    desc: Build backend using vars
    dir: backend
    env:
      GOOS: '{{.GOOS}}'
      GOARCH: '{{.GOARCH}}'
    cmds:
      - task: _build:frontend
      - task: _sync:assets
     # - go clean -cache
      - go build -v -o tmp/main-{{.GOOS}}-{{.GOARCH}}{{.BIN_EXT}} ./cmd/main.go

    


  build:linux-amd:
    desc: Creates a go build for Linux amd64
    cmds:
      - task: _build:backend
        vars: { GOOS: 'linux', GOARCH: 'amd64', BIN_EXT: '' }
  
  build:linux-arm:
    desc: Creates a go build for Linux arm64
    cmds:
      - task: _build:backend
        vars: { GOOS: 'linux', GOARCH: 'arm64', BIN_EXT: '' }

  build:mac-silicon:
    desc: Creates a go build for Apple Silicon
    cmds:
      - task: _build:backend
        vars: { GOOS: 'darwin', GOARCH: 'arm64', BIN_EXT: '' }

  
  