openapi: 3.1.0
info:
  title: KIOSK API
  version: 0.0.2

tags:
  - name: products
  - name: shopping-carts
  - name: users

paths:
  /products:
    get:
      summary: Load all products
      tags:
        - products
      responses:
        '200':
          description: A list of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'

  /shopping-carts:
    post:
      summary: Create a new shopping cart
      tags:
        - shopping-carts
      responses:
        '201':
          description: A shopping cart
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Shopping-Cart'

  /shopping-carts/{id}/increase:
    post:
      summary: Add product to shopping cart
      tags:
        - shopping-carts
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: Shopping Cart ID to use
        - in: query
          name: productID
          schema:
            type: string
          required: true
          description: Product to add to Shopping Cart
      responses:
        '200':
          description: A shopping cart
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Shopping-Cart'


  /shopping-carts/{id}/decrease:
    post:
      summary: Remove product from shopping cart
      tags:
        - shopping-carts
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: Shopping Cart ID to use
        - in: query
          name: productID
          schema:
            type: string
          required: true
          description: Product to remove from Shopping Cart
      responses:
        '200':
          description: A shopping cart
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Shopping-Cart'

  /users/current:
    get:
      summary: Get the currently logged in user
      tags:
        - users
      responses:
        '200':
          description: A user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

components:
  schemas:
    Product:
      type: object
      required:
        - id
        - name
        - price
      properties:
        id:
          type: string
          examples: 
            - "00000000-0000-0000-0000-000000000000"
        name:
          type: string
          examples: 
            - "Example Product"
        price:
          type: number
          examples: 
            - 1.0

    Shopping-Cart:
      type: object
      required:
        - id
        - fullPrice
        - lineItems
        - userId
      properties:
        id:
          type: string
          examples: 
            - "00000000-0000-0000-0000-000000000000"
        fullPrice:
          type: number
          examples: 
            - 10.0
        lineItems: 
          type: array
          items:
            $ref: '#/components/schemas/LineItem'
        userId: 
          type: string
          examples: 
            - "00000000-0000-0000-0000-000000000000"

    LineItem:
      type: object
      required:
        - productId
        - productName
        - amount
        - price
      properties:
        productId:
          type: string
          examples: 
            - "00000000-0000-0000-0000-000000000000"
        productName:
          type: string
          examples: 
            - "Water"
        amount:
          type: integer
          examples: 
            - 5
        price:
          type: number
          examples: 
            - 10.0

    User:
      type: object
      required:
        - userId
        - name
        - balance
        - price
      properties:
        userId:
          type: string
          examples: 
            - "00000000-0000-0000-0000-000000000000"
        name:
          type: string
          examples: 
            - "Max Musterman"
        balance:
          type: number
          examples: 
            - 10.0