openapi: 3.1.0
info:
  title: KIOSK API
  version: 0.0.3

tags:
  - name: products
  - name: shopping-carts
  - name: users
  - name: auth
  - name: pushes
  - name: chargements
  - name: events

paths:

  /events/current:
    post:
      summary: Create a new event and set it as the current one
      tags:
        - events
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateEvent'
      responses:
        '200':
          description: Event created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
    get:
      summary: Get the current event and the event usage of the current user
      tags:
        - events
      responses:
        '200':
          description: Event
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'

    

  /chargements/current:
    post:
      summary: Create a new chargement and set it as the current one
      tags:
        - chargements
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateChargement'
      responses:
        '200':
          description: Payment link generated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Chargement'

  /chargements/current/cancel:
    post:
      summary: Cancel current Chargement
      tags:
        - chargements
      responses:
        '200':
          description: Successfully canceled chargement

  /pushes:
    get:                                
      summary: Subscribe to server sent events
      tags:
        - pushes
      responses:
        '200':
          description: Stream of real time events
          content:
            text/event-stream:
              schema:
                $ref: '#/components/schemas/SSEEvent'



  /products:
    get:
      summary: Load all products
      tags:
        - products
      responses:
        '200':
          description: A list of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'






  /shopping-carts/current:
    post:
      summary: Create a new shopping cart and set it as the current cart
      tags:
        - shopping-carts
      responses:
        '201':
          description: A shopping cart
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Shopping-Cart'

    get:
      summary: Get the current shopping cart
      tags:
        - shopping-carts
      responses:
        '200':
          description: A shopping cart
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Shopping-Cart'

  /shopping-carts/current/increase:
    post:
      summary: Add product to the current shopping cart
      tags:
        - shopping-carts
      parameters:
        - in: query
          name: productID
          schema:
            type: string
          required: true
          description: Product to add to the current Shopping Cart
      responses:
        '200':
          description: A shopping cart
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Shopping-Cart'


  /shopping-carts/current/decrease:
    post:
      summary: Remove product from the current shopping cart
      tags:
        - shopping-carts
      parameters:
        - in: query
          name: productID
          schema:
            type: string
          required: true
          description: Product to remove from the current Shopping Cart
      responses:
        '200':
          description: A shopping cart
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Shopping-Cart'

  /shopping-carts/current/checkout:
    post:
      summary: Check out of the current shopping cart
      tags:
        - shopping-carts
      responses:
        '200':
          description: Successfully checked out of the current shopping cart
          content:
            application/json:
                schema:
                  $ref: '#/components/schemas/Shopping-Cart'




          

  /users/current:
    get:
      summary: Get the currently logged in user
      tags:
        - users
      responses:
        '200':
          description: A user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'






  /auth/usercode:
    post:
      summary: Login with usercode. Only for testing purposes
      tags:
        - auth
      parameters:
        - in: query
          name: usercode
          schema:
            type: string
          required: true
          description: the usercode with which an user can login to the system
      responses:
        '200':
          description: Login successfull

  /auth/logout:
    post:
      summary: Logout current user
      tags:
        - auth
      responses:
        '200':
          description: Logout successfull




  /input/barcode:
    post:
      summary: Use Inputsystem with barcode. Mainly for testing purposes
      tags:
        - input
      parameters:
        - in: query
          name: input
          schema:
            type: string
          required: true
          description: The input which should be inserted with an barcode scanner
      responses:
        '200':
          description: Read

  /input/rfid:
    post:
      summary: Use Inputsystem with rfid. Mainly for testing purposes
      tags:
        - input
      parameters:
        - in: query
          name: input
          schema:
            type: string
          required: true
          description: The input which should be inserted from an rfid sensor
      responses:
        '200':
          description: Read
          

components:
  schemas:
    Product:
      type: object
      required:
        - id
        - name
        - price
      properties:
        id:
          type: string
          examples: 
            - "00000000-0000-0000-0000-000000000000"
        name:
          type: string
          examples: 
            - "Example Product"
        price:
          type: number
          examples: 
            - 1.0

    Shopping-Cart:
      type: object
      required:
        - id
        - fullPrice
        - lineItems
        - userId
        - status
        - transactionId
      properties:
        id:
          type: string
          examples: 
            - "00000000-0000-0000-0000-000000000000"
        fullPrice:
          type: number
          examples: 
            - 10.0
        lineItems: 
          type: array
          items:
            $ref: '#/components/schemas/LineItem'
        userId: 
          type: string
          examples: 
            - "00000000-0000-0000-0000-000000000000"
        status:
          type: string
          examples:
            - "active"
            - "checked-out"
        transactionId: 
          type: string
          examples: 
            - "00000000-0000-0000-0000-000000000000"

    LineItem:
      type: object
      required:
        - productId
        - productName
        - amount
        - price
      properties:
        productId:
          type: string
          examples: 
            - "00000000-0000-0000-0000-000000000000"
        productName:
          type: string
          examples: 
            - "Water"
        amount:
          type: integer
          examples: 
            - 5
        price:
          type: number
          examples: 
            - 10.0

    User:
      type: object
      required:
        - userId
        - name
        - balance
        - price
      properties:
        userId:
          type: string
          examples: 
            - "00000000-0000-0000-0000-000000000000"
        name:
          type: string
          examples: 
            - "Max Musterman"
        balance:
          type: number
          examples: 
            - 10.0

    SSEEvent:
      type: string
      enum: [user.login, shoppingcart.update, chargement_intent.completed]



    

    CreateChargement:
      type: object
      required:
        - amountToAdd
      properties:
        amountToAdd:
          type: number
          examples: 
            - 50.0

    Chargement:
      type: object
      required:
        - paymentLink
        - amount
      properties:
        paymentLink:
          type: string
          examples: 
            - "https://checkout.stripe.com/..."
        amount:
          type: number
          examples: 
            - 50.0


    Event:
      type: object
      required:
        - authorName
        - eventEndDateTime
        - eventUsage
        - availableAmountPerPerson
      properties:
        authorName:
          type: string
          examples: 
            - "Max Musterman"
        eventEndDateTime:
          type: string
          format: date-time
          examples: 
            - "2026-09-13T14:32:28Z"
        eventUsage:
          $ref: '#/components/schemas/EventUsage'
        availableAmountPerPerson:
          type: integer
          examples:
          - 5
            

      
    EventUsage:
      type: object
      required:
        - userId
        - amountUsed
      properties:
        userId:
          type: string
          examples: 
            - "00000000-0000-0000-0000-000000000000"
        amountUsed:
          type: integer
          examples:
            - 2
            
    CreateEvent:
      type: object
      required:
        - amountPerPerson
        - endDateTime
      properties:
        amountPerPerson:
          type: integer
          examples: 
            - 5
        endDateTime:
          type: string
          format: date-time
          examples: 
            - "2026-09-13T14:32:28Z"