// This file is auto-generated by @hey-api/openapi-ts

export { getProducts, type Options } from './sdk.gen';
export type { ClientOptions, GetProductsData, GetProductsResponse, GetProductsResponses, Product } from './types.gen';
