// This file is auto-generated by @hey-api/openapi-ts

export { getProducts, type Options, postShoppingCarts, postShoppingCartsByIdDecrease, postShoppingCartsByIdIncrease } from './sdk.gen';
export type { ClientOptions, GetProductsData, GetProductsResponse, GetProductsResponses, LineItem, PostShoppingCartsByIdDecreaseData, PostShoppingCartsByIdDecreaseResponse, PostShoppingCartsByIdDecreaseResponses, PostShoppingCartsByIdIncreaseData, PostShoppingCartsByIdIncreaseResponse, PostShoppingCartsByIdIncreaseResponses, PostShoppingCartsData, PostShoppingCartsResponse, PostShoppingCartsResponses, Product, ShoppingCart } from './types.gen';
