// This file is auto-generated by @hey-api/openapi-ts

export { getProducts, getUsersCurrent, type Options, postShoppingCarts, postShoppingCartsByIdDecrease, postShoppingCartsByIdIncrease } from './sdk.gen';
export type { ClientOptions, GetProductsData, GetProductsResponse, GetProductsResponses, GetUsersCurrentData, GetUsersCurrentResponse, GetUsersCurrentResponses, LineItem, PostShoppingCartsByIdDecreaseData, PostShoppingCartsByIdDecreaseResponse, PostShoppingCartsByIdDecreaseResponses, PostShoppingCartsByIdIncreaseData, PostShoppingCartsByIdIncreaseResponse, PostShoppingCartsByIdIncreaseResponses, PostShoppingCartsData, PostShoppingCartsResponse, PostShoppingCartsResponses, Product, ShoppingCart, User } from './types.gen';
