// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, ServerSentEventsResult, TDataShape } from './client';
import { client } from './client.gen';
import type { GetProductsData, GetProductsResponses, GetPushesData, GetPushesResponse, GetPushesResponses, GetUsersCurrentData, GetUsersCurrentResponses, PostAuthLogoutData, PostAuthLogoutResponses, PostAuthUsercodeData, PostAuthUsercodeResponses, PostInputBarcodeData, PostInputBarcodeResponses, PostInputRfidData, PostInputRfidResponses, PostShoppingCartsCurrentCheckoutData, PostShoppingCartsCurrentCheckoutResponses, PostShoppingCartsCurrentData, PostShoppingCartsCurrentDecreaseData, PostShoppingCartsCurrentDecreaseResponses, PostShoppingCartsCurrentIncreaseData, PostShoppingCartsCurrentIncreaseResponses, PostShoppingCartsCurrentResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Subscribe to server sent events
 */
export const getPushes = <ThrowOnError extends boolean = false>(options?: Options<GetPushesData, ThrowOnError, GetPushesResponse>): Promise<ServerSentEventsResult<GetPushesResponses>> => (options?.client ?? client).sse.get<GetPushesResponses, unknown, ThrowOnError>({ url: '/pushes', ...options });

/**
 * Load all products
 */
export const getProducts = <ThrowOnError extends boolean = false>(options?: Options<GetProductsData, ThrowOnError>): RequestResult<GetProductsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetProductsResponses, unknown, ThrowOnError>({ url: '/products', ...options });

/**
 * Create a new shopping cart and set it as the current cart
 */
export const postShoppingCartsCurrent = <ThrowOnError extends boolean = false>(options?: Options<PostShoppingCartsCurrentData, ThrowOnError>): RequestResult<PostShoppingCartsCurrentResponses, unknown, ThrowOnError> => (options?.client ?? client).post<PostShoppingCartsCurrentResponses, unknown, ThrowOnError>({ url: '/shopping-carts/current', ...options });

/**
 * Add product to the current shopping cart
 */
export const postShoppingCartsCurrentIncrease = <ThrowOnError extends boolean = false>(options: Options<PostShoppingCartsCurrentIncreaseData, ThrowOnError>): RequestResult<PostShoppingCartsCurrentIncreaseResponses, unknown, ThrowOnError> => (options.client ?? client).post<PostShoppingCartsCurrentIncreaseResponses, unknown, ThrowOnError>({ url: '/shopping-carts/current/increase', ...options });

/**
 * Remove product from the current shopping cart
 */
export const postShoppingCartsCurrentDecrease = <ThrowOnError extends boolean = false>(options: Options<PostShoppingCartsCurrentDecreaseData, ThrowOnError>): RequestResult<PostShoppingCartsCurrentDecreaseResponses, unknown, ThrowOnError> => (options.client ?? client).post<PostShoppingCartsCurrentDecreaseResponses, unknown, ThrowOnError>({ url: '/shopping-carts/current/decrease', ...options });

/**
 * Check out of the current shopping cart
 */
export const postShoppingCartsCurrentCheckout = <ThrowOnError extends boolean = false>(options?: Options<PostShoppingCartsCurrentCheckoutData, ThrowOnError>): RequestResult<PostShoppingCartsCurrentCheckoutResponses, unknown, ThrowOnError> => (options?.client ?? client).post<PostShoppingCartsCurrentCheckoutResponses, unknown, ThrowOnError>({ url: '/shopping-carts/current/checkout', ...options });

/**
 * Get the currently logged in user
 */
export const getUsersCurrent = <ThrowOnError extends boolean = false>(options?: Options<GetUsersCurrentData, ThrowOnError>): RequestResult<GetUsersCurrentResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetUsersCurrentResponses, unknown, ThrowOnError>({ url: '/users/current', ...options });

/**
 * Login with usercode. Only for testing purposes
 */
export const postAuthUsercode = <ThrowOnError extends boolean = false>(options: Options<PostAuthUsercodeData, ThrowOnError>): RequestResult<PostAuthUsercodeResponses, unknown, ThrowOnError> => (options.client ?? client).post<PostAuthUsercodeResponses, unknown, ThrowOnError>({ url: '/auth/usercode', ...options });

/**
 * Logout current user
 */
export const postAuthLogout = <ThrowOnError extends boolean = false>(options?: Options<PostAuthLogoutData, ThrowOnError>): RequestResult<PostAuthLogoutResponses, unknown, ThrowOnError> => (options?.client ?? client).post<PostAuthLogoutResponses, unknown, ThrowOnError>({ url: '/auth/logout', ...options });

/**
 * Use Inputsystem with barcode. Mainly for testing purposes
 */
export const postInputBarcode = <ThrowOnError extends boolean = false>(options: Options<PostInputBarcodeData, ThrowOnError>): RequestResult<PostInputBarcodeResponses, unknown, ThrowOnError> => (options.client ?? client).post<PostInputBarcodeResponses, unknown, ThrowOnError>({ url: '/input/barcode', ...options });

/**
 * Use Inputsystem with rfid. Mainly for testing purposes
 */
export const postInputRfid = <ThrowOnError extends boolean = false>(options: Options<PostInputRfidData, ThrowOnError>): RequestResult<PostInputRfidResponses, unknown, ThrowOnError> => (options.client ?? client).post<PostInputRfidResponses, unknown, ThrowOnError>({ url: '/input/rfid', ...options });
