// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type Product = {
    id: string;
    name: string;
    price: number;
};

export type ShoppingCart = {
    id: string;
    fullPrice: number;
    lineItems: Array<LineItem>;
    userId: string;
    status: string;
    transactionId: string;
};

export type LineItem = {
    productId: string;
    productName: string;
    amount: number;
    price: number;
};

export type User = {
    userId: string;
    name: string;
    balance: number;
};

export type GetProductsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/products';
};

export type GetProductsResponses = {
    /**
     * A list of products
     */
    200: Array<Product>;
};

export type GetProductsResponse = GetProductsResponses[keyof GetProductsResponses];

export type PostShoppingCartsCurrentData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/shopping-carts/current';
};

export type PostShoppingCartsCurrentResponses = {
    /**
     * A shopping cart
     */
    201: ShoppingCart;
};

export type PostShoppingCartsCurrentResponse = PostShoppingCartsCurrentResponses[keyof PostShoppingCartsCurrentResponses];

export type PostShoppingCartsCurrentIncreaseData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Product to add to the current Shopping Cart
         */
        productID: string;
    };
    url: '/shopping-carts/current/increase';
};

export type PostShoppingCartsCurrentIncreaseResponses = {
    /**
     * A shopping cart
     */
    200: ShoppingCart;
};

export type PostShoppingCartsCurrentIncreaseResponse = PostShoppingCartsCurrentIncreaseResponses[keyof PostShoppingCartsCurrentIncreaseResponses];

export type PostShoppingCartsCurrentDecreaseData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Product to remove from the current Shopping Cart
         */
        productID: string;
    };
    url: '/shopping-carts/current/decrease';
};

export type PostShoppingCartsCurrentDecreaseResponses = {
    /**
     * A shopping cart
     */
    200: ShoppingCart;
};

export type PostShoppingCartsCurrentDecreaseResponse = PostShoppingCartsCurrentDecreaseResponses[keyof PostShoppingCartsCurrentDecreaseResponses];

export type PostShoppingCartsCurrentCheckoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/shopping-carts/current/checkout';
};

export type PostShoppingCartsCurrentCheckoutResponses = {
    /**
     * Successfully checked out of the current shopping cart
     */
    200: ShoppingCart;
};

export type PostShoppingCartsCurrentCheckoutResponse = PostShoppingCartsCurrentCheckoutResponses[keyof PostShoppingCartsCurrentCheckoutResponses];

export type GetUsersCurrentData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/current';
};

export type GetUsersCurrentResponses = {
    /**
     * A user
     */
    200: User;
};

export type GetUsersCurrentResponse = GetUsersCurrentResponses[keyof GetUsersCurrentResponses];

export type PostAuthUsercodeData = {
    body?: never;
    path?: never;
    query: {
        /**
         * the usercode with which an user can login to the system
         */
        usercode: string;
    };
    url: '/auth/usercode';
};

export type PostAuthUsercodeResponses = {
    /**
     * Login successfull
     */
    200: unknown;
};

export type PostAuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type PostAuthLogoutResponses = {
    /**
     * Logout successfull
     */
    200: unknown;
};
