// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type Product = {
    id: string;
    name: string;
    price: number;
};

export type GetProductsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/products';
};

export type GetProductsResponses = {
    /**
     * A list of products
     */
    200: Array<Product>;
};

export type GetProductsResponse = GetProductsResponses[keyof GetProductsResponses];
